# Generated by Django 5.0.6 on 2024-05-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('domaine', models.CharField(choices=[('1', 'Informatique'), ('2', 'Architecte'), ('3', 'Bijoutier'), ('4', 'Stagiaire')], max_length=15)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
