# Generated by Django 5.0.6 on 2024-05-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='domaine',
            field=models.CharField(choices=[('', '---- Selectionner un domaine ----'), ('1', 'Informatique'), ('2', 'Architecte'), ('3', 'Bijoutier'), ('4', 'Stagiaire')], max_length=15, null=True),
        ),
    ]
