# Generated by Django 5.0.6 on 2024-05-25 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_employe_domaine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='domaine',
            field=models.CharField(choices=[('', '---- Selectionner un domaine ----'), ('1', 'Informatique'), ('2', 'Architecte'), ('3', 'Bijoutier'), ('4', 'Stagiaire')], max_length=15),
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='dashboard.clientprofile')),
                ('constructors', models.ManyToManyField(to='dashboard.employe')),
            ],
        ),
        migrations.CreateModel(
            name='ImageProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projet_images/')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dashboard.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], max_length=20)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='dashboard.projet')),
            ],
        ),
    ]
