# Generated by Django 5.0.6 on 2024-05-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_employe_domaine_projet_imageprojet_tache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='type',
        ),
    ]
