# Generated by Django 5.0.6 on 2024-06-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_projet_type_projet_projetimage_delete_imageprojet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='domaine',
            field=models.CharField(choices=[('', ' Selectionner un domaine '), ('1', 'Informatique'), ('2', 'Architecte'), ('3', 'Bijoutier'), ('4', 'Stagiaire')], max_length=15),
        ),
        migrations.AlterField(
            model_name='projet',
            name='type_projet',
            field=models.CharField(choices=[('', 'Sélectionner un type de projet'), ('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='projetimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projet_images/'),
        ),
    ]
