# Generated by Django 5.0.6 on 2024-06-02 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_employe_domaine_alter_projet_type_projet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetimage',
            name='caption',
        ),
    ]
