# Generated by Django 5.0.6 on 2024-06-06 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='dashboard.clientprofile'),
        ),
    ]
