# Generated by Django 5.0.6 on 2024-06-06 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_commentaire_client_commentaire_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='user',
            new_name='owner',
        ),
    ]
