# Generated by Django 5.0.6 on 2024-06-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
    ]
